services:
    db:
        image: postgres:16
        env_file: ./.db.env
        ports: ["5432:5432"]
        volumes: [db_data:/var/lib/postgresql/data]

    api:
        build: ./api
        env_file: ./api/.env
        environment:
            DATABASE_URL: ${DATABASE_URL_DOCKER:-postgres://postgres:postgres@db:5432/microapp}
            PORT: 3000
        ports: ["5172:3000"]
        depends_on: [db]

    web:
        build:
            context: ./web
            args:
                VITE_API_URL: http://localhost:5172
        env_file: ./web/.env
        ports: ["3000:80"]
        depends_on: [api]

volumes:
    db_data:
