version: "3.9"
services:
    db:
        image: postgres:16
        env_file: ./.db.env
        ports: ["5432:5432"]
        volumes: [db_data:/var/lib/postgresql/data]

    api:
        build: ./api
        env_file: ./api/.env
        ports: ["3000:3000"]
        depends_on: [db]

    web:
        build: ./web
        env_file: ./web/.env
        ports: ["5173:80"]
        depends_on: [api]

volumes:
    db_data:
